### ISSUE TITLE
TypeError: Cannot read property 'autoUpdater' of undefined at install

### ISSUE THREAD

**Issue by manosim** [jenslind/electron-gh-releases#19]
Hello! When I'm trying to use `updater.install()` but it seems that `updater` is `undefined`. Here you can find the [source code](https://github.com/ekonstantinidis/gitify/blob/release-1.0.0/main.js#L66).
### Details
- Electron 1.0.2
- electron-gh-releases 2.0.3 (Also tried 2.0.2)
### Source Code

```
const updater = new GhReleases(autoUpdateOptions);

updater.on('error', (event, message) => {
  console.log('ERRORED.');
  console.log('Event: ' + JSON.stringify(event) + '. MESSAGE: ' + message);
});

updater.on('update-downloaded', (info) => {
  console.log('Update downloaded');
  confirmAutoUpdate(updater.install);
});
```
#### The Error

```
Uncaught Exception:
TypeError: Cannot read property 'autoUpdater' of undefined
    at install (/Applications/Gitify.app/Contents/Resources/app.asar/node_modules/electron-gh-releases/GhReleases.js:197:11)
    at Function.<anonymous> (/Applications/Gitify.app/Contents/Resources/app.asar/main.js:45:9)
```
#### Screenshots

The value of `updater`:
<img width="532" alt="screen shot 2016-06-02 at 13 44 17" src="https://cloud.githubusercontent.com/assets/6333409/15745276/eb185a1e-28c8-11e6-84b1-38735f360f78.png">

The error:
<img width="504" alt="screen shot 2016-06-02 at 13 44 26" src="https://cloud.githubusercontent.com/assets/6333409/15745280/ef97dc68-28c8-11e6-98be-15f582a311e8.png">
### Update

It looks like it is actually updating the app but it still throws that error

**Comment by manosim** [comment]
Looks like the problem was that I had to pass the `updater` object instead of the `updater.install` function. Works great now!
